version: '3.7'
services:
  server:
    image: openpolicyagent/opa:0.22.0-dev
    ports:
      - 127.0.0.1:8181:8181
    command: run --server --log-level debug --log-format text --bundle example
    volumes:
      - ./example:/example
